import { Command } from "commander"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import pc from "picocolors"
import { assertWriteAllowed } from "@hardened/core"

// Maps a package name to a human-readable description for the "Detected"
// output block. If a user's package.json has the dep, we tell them the rule
// that covers it will fire automatically.
const HTTP_LIBS = new Map<string, string>([
  ["axios", "axios"],
  ["got", "got"],
  ["ky", "ky"],
  ["node-fetch", "node-fetch"],
])

const DB_LIBS = new Map<string, string>([
  ["pg", "pg (node-postgres)"],
  ["mysql2", "mysql2"],
  ["@prisma/client", "Prisma"],
])

export const initCommand = new Command("init")
  .description("Generate a hardened.config.ts tailored to your project.")
  .option("--cwd <dir>", "working directory", process.cwd())
  .option("--force", "overwrite existing hardened.config.ts")
  .action(async (opts) => {
    assertWriteAllowed("init")
    const cwd = resolve(opts.cwd as string)
    const configPath = join(cwd, "hardened.config.ts")
    const pkgPath = join(cwd, "package.json")

    if (existsSync(configPath) && !opts.force) {
      console.error(
        pc.red("✗") +
          ` hardened.config.ts already exists at ${configPath}\n` +
          `  Use ${pc.cyan("--force")} to overwrite.`,
      )
      process.exit(1)
    }

    const detected = detectDependencies(pkgPath)
    const content = renderConfig(detected)

    writeFileSync(configPath, content)

    console.log(
      pc.green("✓") + ` Wrote ${pc.bold("hardened.config.ts")}\n`,
    )

    if (detected.http.length > 0 || detected.db.length > 0) {
      console.log(pc.bold("Detected in your package.json:"))
      for (const lib of detected.http) {
        console.log(`  ${pc.green("•")} ${lib}`)
      }
      for (const lib of detected.db) {
        console.log(`  ${pc.green("•")} ${lib}`)
      }
      console.log()
    } else {
      console.log(
        pc.dim(
          "No known HTTP/DB client dependencies detected. All built-in rules are enabled; ones that don't match your code produce zero findings.",
        ) + "\n",
      )
    }

    console.log(pc.bold("Next steps:"))
    console.log(`  ${pc.cyan("npx hardened risk scan")}   ${pc.dim("# report findings")}`)
    console.log(`  ${pc.cyan("npx hardened risk fix")}    ${pc.dim("# apply auto-fixes")}`)
    console.log(
      `  ${pc.cyan("npx hardened risk fix --pr")} ${pc.dim("# open a draft GitHub PR")}`,
    )
  })

interface Detected {
  http: string[]
  db: string[]
}

export function detectDependencies(pkgPath: string): Detected {
  const result: Detected = { http: [], db: [] }
  if (!existsSync(pkgPath)) return result

  let pkg: {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
    peerDependencies?: Record<string, string>
  }
  try {
    pkg = JSON.parse(readFileSync(pkgPath, "utf8"))
  } catch {
    return result
  }

  const all = {
    ...(pkg.dependencies ?? {}),
    ...(pkg.devDependencies ?? {}),
    ...(pkg.peerDependencies ?? {}),
  }

  for (const [dep, label] of HTTP_LIBS) {
    if (dep in all) result.http.push(label)
  }
  for (const [dep, label] of DB_LIBS) {
    if (dep in all) result.db.push(label)
  }
  return result
}

export function renderConfig(detected: Detected): string {
  const libs = [...detected.http, ...detected.db]
  const header =
    libs.length > 0
      ? `// Generated by \`hardened init\`.\n// Detected libraries in your package.json: ${libs.join(", ")}\n// All built-in rules are enabled — rules that don't match your code produce zero findings.`
      : `// Generated by \`hardened init\`.\n// No known HTTP/DB client dependencies detected; all built-in rules enabled anyway.`

  return `${header}
import { defineConfig } from "hardened"

export default defineConfig({
  rules: {
    "risk/http-no-timeout": "error",
    "risk/fetch-no-abort-signal": "warning",
    "risk/floating-promise": "warning",
    "risk/await-in-loop": "warning",
    "risk/promise-all-no-settled": "info",
    "risk/db-no-query-timeout": "error",
    "risk/prisma-no-timeout": "error",
  },
  ignore: [
    // Build output
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/.next/**",
    "**/.turbo/**",
    "**/coverage/**",
    // Test files
    "**/*.test.ts",
    "**/*.test.tsx",
    "**/*.test.js",
    "**/*.test.jsx",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.spec.js",
    "**/*.spec.jsx",
    // Test / E2E directories
    "**/tests/**",
    "**/test/**",
    "**/__tests__/**",
    "**/__mocks__/**",
    "**/e2e/**",
    // Fixtures / test corpora
    "**/fixtures/**",
    "**/__fixtures__/**",
    // One-shot tooling (sequential awaits are expected here)
    "**/scripts/**",
    "**/ops/**",
    "**/tools/**",
    "**/seed-*",
    "**/seeds/**",
    "**/migrations/**",
    // Archived / legacy code
    "**/archive/**",
    "**/archived/**",
    "**/legacy/**",
  ],
  runtime: {
    defaults: {
      timeout: 10_000,
      retries: 3,
      backoff: "exponential",
    },
  },
})
`
}
