import { Octokit } from "@octokit/rest"
import simpleGit, { type SimpleGit } from "simple-git"
import { execSync } from "node:child_process"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { Fixer, type Match, type ResolvedConfig, type Rule } from "@hardened/core"
import { CLI_VERSION } from "../version.js"

export interface PROptions {
  cwd: string
  findings: Match[]
  rules: Rule[]
  config: ResolvedConfig
}

/**
 * End-to-end draft-PR flow:
 *   1. Validate git state (clean working tree, GitHub remote, auth token)
 *   2. Create a new branch `hardened/auto-fix-<timestamp>`
 *   3. Apply fixes to disk
 *   4. Update package.json with any newly added runtime dependencies
 *   5. git add + commit with a conventional-commits message
 *   6. Push the branch to origin
 *   7. Open a draft pull request against the default branch
 *   8. Restore the working tree to the original branch
 *
 * On any failure, attempts to restore the original branch and delete the
 * created feature branch so the user's local state is unchanged.
 */
export async function generatePR(opts: PROptions): Promise<void> {
  const git = simpleGit(opts.cwd)

  const { owner, repo } = await validateGitState(git)
  const token = resolveToken()
  const octokit = new Octokit({ auth: token })

  const existingPr = await findOpenHardenedPR(octokit, owner, repo)
  if (existingPr) {
    throw new Error(
      `PR #${existingPr.number} already open - close or merge before running again.\n` +
        `  What you can do: review ${existingPr.html_url}, then close or merge it before rerunning --pr.`,
    )
  }

  const timestamp = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d+Z$/, "")
    .replace("T", "-")
  const branchName = `hardened/auto-fix-${timestamp}`

  const status = await git.status()
  const originalBranch = status.current
  if (!originalBranch) {
    throw new Error(
      "Could not determine current branch (detached HEAD?).\n" +
        "  What you can do: check out a named branch before running with --pr.",
    )
  }

  console.log(`Creating branch ${branchName}…`)
  await git.checkoutLocalBranch(branchName)

  try {
    // Apply fixes now that we're on the feature branch. Writes to disk,
    // mutates source files in-place.
    const fixer = new Fixer({
      findings: opts.findings,
      rules: opts.rules,
      config: opts.config,
      dryRun: false,
    })
    const result = await fixer.apply()

    if (result.fixesApplied === 0) {
      throw new Error(
        "No fixable findings. Nothing to commit. (Finding-only warnings are skipped from auto-fix.)\n" +
          "  What you can do: run `hardened risk scan` and review finding-only rules manually.",
      )
    }

    updateHostPackageJson(opts.cwd, result.addedDependencies)

    console.log(`Committing ${result.fixesApplied} fix${result.fixesApplied === 1 ? "" : "es"}…`)
    await git.add(".")
    const commitMessage = buildCommitMessage(result, opts.findings)
    await git.commit(commitMessage)

    console.log(`Pushing ${branchName} to origin…`)
    await git.push(["-u", "origin", branchName])

    console.log("Opening draft PR…")
    const { data: repoInfo } = await octokit.repos.get({ owner, repo })
    const base = repoInfo.default_branch

    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      head: branchName,
      base,
      draft: true,
      title: buildPRTitle(result),
      body: buildPRBody(result, opts.findings),
    })

    console.log(`\n✓ Draft PR opened: ${pr.html_url}`)
    console.log(`  Branch: ${branchName} → ${base}`)
    console.log(`  Fixes:  ${result.fixesApplied}`)
    if (result.addedDependencies.length > 0) {
      console.log(
        `  Deps:   ${result.addedDependencies.map((d) => `${d.name}@${d.version}`).join(", ")}`,
      )
    }

    await git.checkout(originalBranch)
    console.log(`  Restored ${originalBranch} (changes live on ${branchName}).`)
  } catch (err) {
    await safeRollback(git, originalBranch, branchName)
    throw err
  }
}

export async function findOpenHardenedPR(
  octokit: Pick<Octokit, "pulls">,
  owner: string,
  repo: string,
): Promise<{ number: number; html_url: string } | null> {
  const { data: pulls } = await octokit.pulls.list({
    owner,
    repo,
    state: "open",
    per_page: 100,
  })

  const pr = pulls.find((pull) => {
    const branch = pull.head.ref
    const body = pull.body ?? ""
    return (
      branch.startsWith("hardened/auto-fix-") &&
      body.includes("Generated by [hardened]")
    )
  })

  return pr ? { number: pr.number, html_url: pr.html_url } : null
}

async function validateGitState(
  git: SimpleGit,
): Promise<{ owner: string; repo: string }> {
  const isRepo = await git.checkIsRepo()
  if (!isRepo) {
    throw new Error(
      "Not inside a git repository.\n" +
        "  What you can do: run `git init` first or use `hardened risk fix` without --pr.",
    )
  }

  const status = await git.status()
  if (!status.isClean()) {
    const count =
      status.modified.length +
      status.not_added.length +
      status.staged.length +
      status.deleted.length
    throw new Error(
      `Working tree has ${count} uncommitted change${count === 1 ? "" : "s"}. ` +
        `Commit or stash them before running with --pr, so the PR contains only hardened's edits.\n` +
        "  What you can do: commit, stash, or rerun without --pr to keep fixes local.",
    )
  }

  const remotes = await git.getRemotes(true)
  const origin = remotes.find((r) => r.name === "origin")
  if (!origin) {
    throw new Error(
      "No `origin` remote configured.\n" +
        "  What you can do: run `git remote add origin git@github.com:owner/repo.git` first.",
    )
  }

  const pushUrl = origin.refs.push
  const parsed = parseGithubRemote(pushUrl)
  if (!parsed) {
    throw new Error(
      `Remote 'origin' is not a GitHub repository (got: ${pushUrl}). The --pr flag only supports GitHub.\n` +
        "  What you can do: use a GitHub origin remote or run `hardened risk fix` without --pr.",
    )
  }
  return parsed
}

function parseGithubRemote(url: string): { owner: string; repo: string } | null {
  if (!url) return null
  // Matches: https://github.com/owner/repo(.git) or git@github.com:owner/repo(.git)
  const m = url.match(/github\.com[:/]([^/]+)\/([^/]+?)(?:\.git)?$/)
  if (!m) return null
  return { owner: m[1]!, repo: m[2]! }
}

function resolveToken(): string {
  const fromEnv = process.env.GITHUB_TOKEN || process.env.GH_TOKEN
  if (fromEnv) return fromEnv

  try {
    const out = execSync("gh auth token", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    })
    const trimmed = out.trim()
    if (trimmed) return trimmed
  } catch {
    // Fall through to the error below
  }

  throw new Error(
    "No GitHub token found. Set GITHUB_TOKEN or sign in with `gh auth login` first. " +
      "The token needs `repo` scope to push branches and open PRs.\n" +
      "  What you can do: run `gh auth login` or export GITHUB_TOKEN.",
  )
}

function updateHostPackageJson(
  cwd: string,
  deps: Array<{ name: string; version: string }>,
): void {
  if (deps.length === 0) return
  const pkgPath = join(cwd, "package.json")
  if (!existsSync(pkgPath)) return

  const pkgRaw = readFileSync(pkgPath, "utf8")
  const pkg = JSON.parse(pkgRaw) as {
    dependencies?: Record<string, string>
  }
  pkg.dependencies = pkg.dependencies ?? {}
  for (const d of deps) {
    if (!pkg.dependencies[d.name]) {
      pkg.dependencies[d.name] = d.version
    }
  }
  // Preserve trailing newline if original had one.
  const trailing = pkgRaw.endsWith("\n") ? "\n" : ""
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + trailing)
}

function buildCommitMessage(
  result: { fixesApplied: number; filesChanged: string[]; skipped: Match[] },
  allFindings: Match[],
): string {
  const counts = countByRule(allFindings)
  const lines: string[] = []
  lines.push(`fix: apply hardened auto-fixes (${result.fixesApplied} findings)`)
  lines.push("")
  lines.push(
    `Automated timeout fixes applied by hardened v${CLI_VERSION}.`,
  )
  lines.push("")
  lines.push(`Files changed: ${result.filesChanged.length}`)
  lines.push(`Fixes applied: ${result.fixesApplied}`)
  lines.push(`Findings skipped (no auto-fix): ${result.skipped.length}`)
  lines.push("")
  lines.push("Findings by rule:")
  for (const [rule, count] of counts.entries()) {
    lines.push(`  ${rule}: ${count}`)
  }
  return lines.join("\n")
}

function buildPRTitle(result: { fixesApplied: number }): string {
  const n = result.fixesApplied
  return `fix: apply ${n} hardened auto-fix${n === 1 ? "" : "es"}`
}

function buildPRBody(
  result: { fixesApplied: number; filesChanged: string[]; skipped: Match[]; addedDependencies: Array<{ name: string; version: string }> },
  allFindings: Match[],
): string {
  const counts = countByRule(allFindings)
  const lines: string[] = []

  lines.push("## Summary")
  lines.push("")
  lines.push(
    `Generated by [hardened](https://github.com/compactbench/hardened) v${CLI_VERSION} — a deterministic linter/codemod for unbounded TypeScript I/O.`,
  )
  lines.push("")
  lines.push(
    `**${result.fixesApplied}** fix${result.fixesApplied === 1 ? "" : "es"} applied across **${result.filesChanged.length}** file${result.filesChanged.length === 1 ? "" : "s"}.`,
  )
  lines.push("")

  lines.push("## Findings by rule")
  lines.push("")
  lines.push("| Rule | Count |")
  lines.push("| --- | ---: |")
  for (const [rule, count] of counts.entries()) {
    lines.push(`| \`${rule}\` | ${count} |`)
  }
  lines.push("")

  if (result.addedDependencies.length > 0) {
    lines.push("## Dependencies added")
    lines.push("")
    for (const d of result.addedDependencies) {
      lines.push(`- \`${d.name}@${d.version}\``)
    }
    lines.push("")
    lines.push(
      "Your package manager's lockfile is NOT yet updated. Run `npm install` (or your equivalent) after merge.",
    )
    lines.push("")
  }

  if (result.skipped.length > 0) {
    lines.push("## Findings without auto-fix")
    lines.push("")
    lines.push(
      `${result.skipped.length} finding${result.skipped.length === 1 ? " was" : "s were"} surfaced as warnings but not rewritten (finding-only rules require human review):`,
    )
    lines.push("")
    const bySkip = countByRule(result.skipped)
    for (const [rule, count] of bySkip.entries()) {
      lines.push(`- \`${rule}\`: ${count}`)
    }
    lines.push("")
  }

  lines.push("## Reviewer checklist")
  lines.push("")
  lines.push("- [ ] Run your test suite against this branch")
  lines.push("- [ ] Review the diff for unexpected behavior changes")
  lines.push("- [ ] Verify added dependencies are acceptable")
  lines.push("- [ ] Check that auto-fixed call sites still match your logging / retry conventions")

  return lines.join("\n")
}

function countByRule(findings: Match[]): Map<string, number> {
  const counts = new Map<string, number>()
  for (const f of findings) {
    counts.set(f.ruleId, (counts.get(f.ruleId) ?? 0) + 1)
  }
  return counts
}

async function safeRollback(
  git: SimpleGit,
  originalBranch: string,
  branchName: string,
): Promise<void> {
  try {
    await git.checkout(["-f", originalBranch])
  } catch {
    // Best effort
  }
  try {
    await git.deleteLocalBranch(branchName, true)
  } catch {
    // Best effort
  }
}
