import { describe, expect, it } from "vitest"
import { findOpenHardenedPR } from "../src/pr/generate.js"

describe("--pr idempotency", () => {
  it("finds an existing open hardened auto-fix PR", async () => {
    const octokit = {
      pulls: {
        list: async () => ({
          data: [
            {
              number: 12,
              html_url: "https://github.com/example/repo/pull/12",
              head: { ref: "feature/manual" },
              body: "manual change",
            },
            {
              number: 13,
              html_url: "https://github.com/example/repo/pull/13",
              head: { ref: "hardened/auto-fix-20260420-010000" },
              body: "Generated by [hardened](https://github.com/compactbench/hardened)",
            },
          ],
        }),
      },
    }

    await expect(
      findOpenHardenedPR(octokit as never, "example", "repo"),
    ).resolves.toEqual({
      number: 13,
      html_url: "https://github.com/example/repo/pull/13",
    })
  })

  it("ignores unrelated open PRs", async () => {
    const octokit = {
      pulls: {
        list: async () => ({
          data: [
            {
              number: 14,
              html_url: "https://github.com/example/repo/pull/14",
              head: { ref: "hardened/manual-test" },
              body: "Generated by [hardened](https://github.com/compactbench/hardened)",
            },
          ],
        }),
      },
    }

    await expect(
      findOpenHardenedPR(octokit as never, "example", "repo"),
    ).resolves.toBeNull()
  })
})
